### Numpy Programming

In [2]:
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.shape)
print(a.ndim) # dimension of the array(no of columns) a -> m x n (m = columns and n = rows)
print(a.size) 
a[0] = 5 #immutable
a

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3


array([5, 2, 3])

In [7]:
c = np.array([[1, 2, 3], [4, 5, 6]]) # Define a rank 2 array (matrix) using a nested list
print(c.shape)                       # Prints (2, 3)
print(c.size)                        # Prints 6
print(c[0, 0], c[0, 1], c[1, 0])

(2, 3)
6
1 2 4


In [12]:
a = np.array([[1, 2], [3, 4]]) # Define a 2x2 matrix
a

array([[1, 2],
       [3, 4]])

In [14]:
a = np.zeros((2,2))
a = np.ones()

array([[0., 0.],
       [0., 0.]])

In [15]:
b = np.zeros((2, 2))                        # Define an array of all zeros
print(b)                                    # Prints [[ 0.  0.]
                                            #         [ 0.  0.]]

c = np.ones((1, 2))                         # Define an array of all ones
print(c)                                    # Prints [[ 1.  1.]]

d = np.full((2, 2), 7)                      # Define a constant array
print(d)                                    # Prints [[ 7.  7.]
                                            #         [ 7.  7.]]

e = np.eye(2)                               # Define a 2x2 identity matrix
print(e)   

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [19]:
np.empty((2,2))

array([[1., 0.],
       [0., 1.]])

In [20]:
g = np.empty((2, 2), dtype=int) 
g

array([[4607182418800017408,                   0],
       [                  0, 4607182418800017408]])

In [28]:
h = np.random.random((2, 2))                # Define a 2x2 matrix from the uniform distribution [0, 1)
print(h)

[[0.45991419 0.14463398]
 [0.50663068 0.51269285]]


In [54]:
import pandas as pd
pd.DataFrame.from_records(np.random.random((10,3)))

0         1         2
0  0.597975  0.675313  0.548495
1  0.662007  0.078371  0.577886
2  0.095167  0.219112  0.848121
3  0.920803  0.441665  0.835954
4  0.196979  0.663367  0.416802
5  0.544086  0.779514  0.846865
6  0.335465  0.466620  0.231008
7  0.455877  0.184411  0.754630
8  0.082487  0.439792  0.182116
9  0.129641  0.500831  0.646595

In [33]:
np.random.randn(10)

array([-1.44734125, -0.17396679, -1.55791864,  0.49800874, -0.32619892,
        1.09898162, -0.05286624,  0.80235303,  2.18827852, -0.85294899])

In [58]:
### Indexing
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [59]:
[(idx,value) for idx,value in enumerate(a)]

[(0, array([1, 2])), (1, array([3, 4]))]